name: ciTest2MGomezJCastilloJ

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # CORRER TESTS
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      #- run: npm install

      # Run tests
      - run: npm ci
      - run: npm run test:prod
    
      # inicio docker
      -
        name: set up ciTest2MGomezJCastilloJ
        uses: docker/setup-qemu-action@v2
      -
        name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test2angular:latest
